// Generated by gencpp from file multi_agent_system/PlanExecutionRequest.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONREQUEST_H
#define MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_agent_system
{
template <class ContainerAllocator>
struct PlanExecutionRequest_
{
  typedef PlanExecutionRequest_<ContainerAllocator> Type;

  PlanExecutionRequest_()
    : plan()  {
    }
  PlanExecutionRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanExecutionRequest_

typedef ::multi_agent_system::PlanExecutionRequest_<std::allocator<void> > PlanExecutionRequest;

typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionRequest > PlanExecutionRequestPtr;
typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionRequest const> PlanExecutionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plan == rhs.plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_agent_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc50643e78ec83e6cd11adcd6225ad09";
  }

  static const char* value(const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc50643e78ec83e6ULL;
  static const uint64_t static_value2 = 0xcd11adcd6225ad09ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_agent_system/PlanExecutionRequest";
  }

  static const char* value(const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string plan\n"
;
  }

  static const char* value(const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanExecutionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_agent_system::PlanExecutionRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONREQUEST_H
