// Generated by gencpp from file multi_agent_system/PlanExecution.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTION_H
#define MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTION_H

#include <ros/service_traits.h>


#include <multi_agent_system/PlanExecutionRequest.h>
#include <multi_agent_system/PlanExecutionResponse.h>


namespace multi_agent_system
{

struct PlanExecution
{

typedef PlanExecutionRequest Request;
typedef PlanExecutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanExecution
} // namespace multi_agent_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_agent_system::PlanExecution > {
  static const char* value()
  {
    return "47835fb064640c5de7faddad2f012e70";
  }

  static const char* value(const ::multi_agent_system::PlanExecution&) { return value(); }
};

template<>
struct DataType< ::multi_agent_system::PlanExecution > {
  static const char* value()
  {
    return "multi_agent_system/PlanExecution";
  }

  static const char* value(const ::multi_agent_system::PlanExecution&) { return value(); }
};


// service_traits::MD5Sum< ::multi_agent_system::PlanExecutionRequest> should match
// service_traits::MD5Sum< ::multi_agent_system::PlanExecution >
template<>
struct MD5Sum< ::multi_agent_system::PlanExecutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_agent_system::PlanExecution >::value();
  }
  static const char* value(const ::multi_agent_system::PlanExecutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_agent_system::PlanExecutionRequest> should match
// service_traits::DataType< ::multi_agent_system::PlanExecution >
template<>
struct DataType< ::multi_agent_system::PlanExecutionRequest>
{
  static const char* value()
  {
    return DataType< ::multi_agent_system::PlanExecution >::value();
  }
  static const char* value(const ::multi_agent_system::PlanExecutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_agent_system::PlanExecutionResponse> should match
// service_traits::MD5Sum< ::multi_agent_system::PlanExecution >
template<>
struct MD5Sum< ::multi_agent_system::PlanExecutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_agent_system::PlanExecution >::value();
  }
  static const char* value(const ::multi_agent_system::PlanExecutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_agent_system::PlanExecutionResponse> should match
// service_traits::DataType< ::multi_agent_system::PlanExecution >
template<>
struct DataType< ::multi_agent_system::PlanExecutionResponse>
{
  static const char* value()
  {
    return DataType< ::multi_agent_system::PlanExecution >::value();
  }
  static const char* value(const ::multi_agent_system::PlanExecutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTION_H
