// Generated by gencpp from file multi_agent_system/PlanExecutionResponse.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONRESPONSE_H
#define MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_agent_system
{
template <class ContainerAllocator>
struct PlanExecutionResponse_
{
  typedef PlanExecutionResponse_<ContainerAllocator> Type;

  PlanExecutionResponse_()
    : success(false)
    , execution_details()  {
    }
  PlanExecutionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , execution_details(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _execution_details_type;
  _execution_details_type execution_details;





  typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanExecutionResponse_

typedef ::multi_agent_system::PlanExecutionResponse_<std::allocator<void> > PlanExecutionResponse;

typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionResponse > PlanExecutionResponsePtr;
typedef boost::shared_ptr< ::multi_agent_system::PlanExecutionResponse const> PlanExecutionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator1> & lhs, const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.execution_details == rhs.execution_details;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator1> & lhs, const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_agent_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a45bb69cb171fde9d7e78595dbfb9ca7";
  }

  static const char* value(const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa45bb69cb171fde9ULL;
  static const uint64_t static_value2 = 0xd7e78595dbfb9ca7ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_agent_system/PlanExecutionResponse";
  }

  static const char* value(const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string execution_details\n"
;
  }

  static const char* value(const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.execution_details);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanExecutionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_agent_system::PlanExecutionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "execution_details: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.execution_details);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_PLANEXECUTIONRESPONSE_H
