// Generated by gencpp from file multi_agent_system/StabilityAnalysisRequest.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_STABILITYANALYSISREQUEST_H
#define MULTI_AGENT_SYSTEM_MESSAGE_STABILITYANALYSISREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_agent_system
{
template <class ContainerAllocator>
struct StabilityAnalysisRequest_
{
  typedef StabilityAnalysisRequest_<ContainerAllocator> Type;

  StabilityAnalysisRequest_()
    : task()  {
    }
  StabilityAnalysisRequest_(const ContainerAllocator& _alloc)
    : task(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StabilityAnalysisRequest_

typedef ::multi_agent_system::StabilityAnalysisRequest_<std::allocator<void> > StabilityAnalysisRequest;

typedef boost::shared_ptr< ::multi_agent_system::StabilityAnalysisRequest > StabilityAnalysisRequestPtr;
typedef boost::shared_ptr< ::multi_agent_system::StabilityAnalysisRequest const> StabilityAnalysisRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_agent_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ece8f504419f7ca4d91b277e47ff617";
  }

  static const char* value(const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ece8f504419f7caULL;
  static const uint64_t static_value2 = 0x4d91b277e47ff617ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_agent_system/StabilityAnalysisRequest";
  }

  static const char* value(const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task\n"
;
  }

  static const char* value(const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StabilityAnalysisRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_agent_system::StabilityAnalysisRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_STABILITYANALYSISREQUEST_H
