// Generated by gencpp from file multi_agent_system/ValidateRequestResponse.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTRESPONSE_H
#define MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_agent_system
{
template <class ContainerAllocator>
struct ValidateRequestResponse_
{
  typedef ValidateRequestResponse_<ContainerAllocator> Type;

  ValidateRequestResponse_()
    : is_standard(false)
    , validation_details()
    , disassembly_plan()  {
    }
  ValidateRequestResponse_(const ContainerAllocator& _alloc)
    : is_standard(false)
    , validation_details(_alloc)
    , disassembly_plan(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_standard_type;
  _is_standard_type is_standard;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _validation_details_type;
  _validation_details_type validation_details;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _disassembly_plan_type;
  _disassembly_plan_type disassembly_plan;





  typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ValidateRequestResponse_

typedef ::multi_agent_system::ValidateRequestResponse_<std::allocator<void> > ValidateRequestResponse;

typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestResponse > ValidateRequestResponsePtr;
typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestResponse const> ValidateRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator1> & lhs, const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_standard == rhs.is_standard &&
    lhs.validation_details == rhs.validation_details &&
    lhs.disassembly_plan == rhs.disassembly_plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator1> & lhs, const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_agent_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c9586279621998d8df57d09408c8ff8";
  }

  static const char* value(const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c9586279621998dULL;
  static const uint64_t static_value2 = 0x8df57d09408c8ff8ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_agent_system/ValidateRequestResponse";
  }

  static const char* value(const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_standard\n"
"string validation_details\n"
"string disassembly_plan\n"
"\n"
;
  }

  static const char* value(const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_standard);
      stream.next(m.validation_details);
      stream.next(m.disassembly_plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidateRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_agent_system::ValidateRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_standard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_standard);
    s << indent << "validation_details: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.validation_details);
    s << indent << "disassembly_plan: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.disassembly_plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTRESPONSE_H
