// Generated by gencpp from file multi_agent_system/ValidateRequestRequest.msg
// DO NOT EDIT!


#ifndef MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTREQUEST_H
#define MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_agent_system
{
template <class ContainerAllocator>
struct ValidateRequestRequest_
{
  typedef ValidateRequestRequest_<ContainerAllocator> Type;

  ValidateRequestRequest_()
    : request()  {
    }
  ValidateRequestRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ValidateRequestRequest_

typedef ::multi_agent_system::ValidateRequestRequest_<std::allocator<void> > ValidateRequestRequest;

typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestRequest > ValidateRequestRequestPtr;
typedef boost::shared_ptr< ::multi_agent_system::ValidateRequestRequest const> ValidateRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator1> & lhs, const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_agent_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_agent_system/ValidateRequestRequest";
  }

  static const char* value(const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
;
  }

  static const char* value(const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidateRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_agent_system::ValidateRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AGENT_SYSTEM_MESSAGE_VALIDATEREQUESTREQUEST_H
